---
- name: Provisioning Jurassic Park Data Terminal
  hosts: target_nodes
  tasks:
    - name: Create the restricted data directory
      ansible.builtin.file:
        path: /etc/ingen_secrets
        state: directory
        mode: '0700'

    - name: Deploy the Cryo-Canister schematics
      ansible.builtin.copy:
        dest: /etc/ingen_secrets/top_secret.txt
        content: |
          PROJECT: NEBRY
          STATUS: IN PROGRESS
          MESSAGE: "Ah, ah, ah! You didn't say the magic word!"
        mode: '0400'
